<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertCartdetailsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::unprepared("
			INSERT INTO cartdetails values('1','1','Main','DG','5','7','1','5','32','48','21','29.7','4','4','di lipet setelahnya','42','2','11','4','2','2','0','25','5','5','0','100000',now(),now());
			INSERT INTO cartdetails values('2','2','Main','OF','1','2','1','2','30.5','44','20.5','29.2','4','4','jangan lupa di sisir','2800','300','700','4','2','2','0','2','2','1','0','158000',now(),now());
			INSERT INTO cartdetails values('3','3','Cover','OF','1','2','1','2','30.5','44','29.2','41','4','4','laminating gloss','2800','300','700','4','2','2','0','1','1','1','0','400000',now(),now());
			INSERT INTO cartdetails values('4','3','Main','OF','1','5','1','2','30.5','44','29.2','41','4','4','susun anom, lipet anom bacok, jilid staples','2700','200','675','4','2','2','0','1','1','1','0','400000',now(),now());
			INSERT INTO cartdetails values('5','4','Main','DG','5','5','1','2','30.5','44','29.2','41','4','4','susun anom, lipet anom bacok, jilid staples','2700','200','675','4','2','2','0','1','1','1','0','400000',now(),now());

			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('15', 'Main', 'OF', '5', '7', '10', '4', '3.08', '4', '2.08', '2', '4', '0', ' ', '9800', '20', '2450', '4', '1', '4', '0', '19', '3', '6', '1', '13462738', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('16', 'Cover', 'DG', '5', '7', '8', '4', '6.09', '5', '5.09', '2.5', '4', '0', ' ', '4800', '157', '1200', '12', '2', '6', '0', '14', '3', '4', '2', '15628569', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('17', 'Isi', 'DG', '3', '1', '7', '1', '7.6', '6', '6.6', '3', '4', '0', ' ', '3300', '61', '825', '4', '1', '4', '0', '25', '4', '6', '1', '9392235', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('15', 'Isi', 'DG', '4', '6', '1', '5', '6.35', '6', '5.35', '3', '2', '3', ' ', '1100', '22', '275', '9', '3', '3', '0', '8', '1', '8', '0', '14367962', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('16', 'Amplop', 'DG', '3', '7', '1', '2', '6.82', '8', '5.82', '4', '4', '1', ' ', '2700', '189', '675', '9', '3', '3', '0', '17', '2', '8', '1', '18083263', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('16', 'Dalam', 'OF', '1', '1', '9', '7', '7.63', '6', '6.63', '3', '1', '3', ' ', '4300', '198', '1075', '25', '3', '8', '1', '12', '4', '3', '0', '19929345', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('17', 'Luar', 'OF', '5', '6', '7', '7', '7.76', '3', '6.76', '1.5', '1', '0', ' ', '7100', '130', '1775', '21', '4', '5', '1', '8', '2', '3', '2', '18387664', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('5', 'Main', 'DG', '4', '7', '8', '4', '6.85', '6', '5.85', '3', '3', '2', ' ', '2000', '140', '500', '18', '3', '6', '0', '15', '2', '7', '1', '19140449', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('6', 'Main', 'OF', '3', '2', '4', '1', '3.21', '6', '2.21', '3', '3', '0', ' ', '1800', '92', '450', '9', '1', '8', '1', '4', '2', '1', '2', '8274360', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('7', 'Main', 'DG', '4', '1', '6', '1', '7.08', '6', '6.08', '3', '4', '2', ' ', '7400', '37', '1850', '6', '2', '3', '0', '22', '3', '7', '1', '1481583', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('8', 'Main', 'OF', '2', '6', '8', '6', '7.84', '8', '6.84', '4', '1', '0', ' ', '1300', '63', '325', '17', '2', '8', '1', '5', '2', '2', '1', '14351496', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('9', 'Main', 'OF', '2', '7', '9', '3', '5.12', '4', '4.12', '2', '3', '3', ' ', '3500', '130', '875', '2', '1', '2', '0', '20', '3', '6', '2', '11328714', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('10', 'Main', 'PL', '3', '5', '8', '1', '4.71', '1', '3.71', '0.5', '2', '1', ' ', '3000', '46', '750', '15', '3', '5', '0', '16', '3', '5', '1', '7489629', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('11', 'Main', 'PL', '3', '5', '2', '1', '3.03', '6', '2.03', '3', '4', '3', ' ', '5400', '34', '1350', '8', '1', '8', '0', '5', '2', '2', '1', '3159712', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('12', 'Main', 'PL', '2', '5', '5', '7', '5.49', '3', '4.49', '1.5', '2', '0', ' ', '2800', '132', '700', '25', '4', '6', '1', '4', '4', '1', '0', '9557715', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('13', 'Main', 'LL', '1', '1', '8', '4', '5.65', '3', '4.65', '1.5', '2', '1', ' ', '9900', '50', '2475', '9', '4', '2', '1', '16', '2', '8', '0', '14910494', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('14', 'Main', 'LL', '6', '5', '1', '5', '1.69', '6', '0.69', '3', '1', '1', ' ', '3000', '198', '750', '9', '1', '8', '1', '29', '4', '7', '1', '8033588', now(), now());


			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('18', 'Main', 'LL', '6', '5', '1', '5', '1.69', '6', '0.69', '3', '1', '1', ' ', '3000', '198', '750', '9', '1', '8', '1', '29', '4', '7', '1', '8033588', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('19', 'Buku', 'LL', '6', '5', '1', '5', '1.69', '6', '0.69', '3', '1', '1', ' ', '3000', '198', '750', '9', '1', '8', '1', '29', '4', '7', '1', '1', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('20', 'Utama', 'LL', '6', '5', '1', '5', '1.69', '6', '0.69', '3', '1', '1', ' ', '3000', '198', '750', '9', '1', '8', '1', '29', '4', '7', '1', '10000', now(), now());
		");
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		//
	}
}
