<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertCartheadersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::unprepared("
			INSERT INTO cartheaders VALUES ('1', '1', '2', 'ClubMed', '10', 'box', 'nanti diambil setelah makan siang', 'file 1 untuk sisi belakang, file 2 untuk sisi depan, nama di excel', '', '', '', '200000', '250000', '0', '0', 'std', '2', '1', '1', '0', '1', '5', '1', now(), now(), null);
			INSERT INTO cartheaders VALUES ('2', '2', '1', 'ClubMed HSBC', '2500', 'lembar', 'dibungkus dengan plastik', '', '', '', '', '1500000', '1800000', '35000', '0', 'exp', '3', '2', '1', '0', '5', '20', '0', now(), now(), null);
			INSERT INTO cartheaders VALUES ('3', '1', '1', 'Booklet KIA', '2500', 'lembar', 'jilid staples 2 mata', '', '', '', '', '5000000', '6000000', '135000', '100000', 'std', '7', '2', '2', '1', '40', '100', '1', now(), now(), null);
			INSERT INTO cartheaders VALUES ('4', '1', '2', 'Booklet KIA Ramadhan Biru Kuning', '1500', 'lembar', 'jilid staples 2 mata', '', '', '', '', '50000000', '6000033', '1350003', '100000', 'std', '7', '2', '3', '1', '40', '100', '1', now(), now(), null);
			INSERT INTO cartheaders VALUES ('5', '2', '2', 'Booklet KIA Ramadhan Biru Kuning', '2000', 'lembar', 'jilid staples 2 mata', '', '', '', '', '50000000', '6000043', '1370003', '100000', 'std', '7', '2', '3', '1', '40', '100', '1', now(), now(), null);
			INSERT INTO cartheaders VALUES ('6', '3', '2', 'Bukalapak Guidance', '250000', 'lembar', 'jilid staples 2 mata', '', '', '', '', '50000000', '8000000', '1350000', '100000', 'std', '7', '2', '3', '1', '40', '100', '1', now(), now(), null);
			INSERT INTO cartheaders VALUES ('7', '3', '2', 'Tokopedia Guide', '2050500', 'lembar', 'jilid staples 2 mata', '', '', '', '', '60000000', '4000000', '1350000', '100000', 'std', '7', '2', '3', '1', '40', '100', '1', now(), now(), null);

			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('1', '1', 'Lebaran Haji 2018', '1000', 'lembar', 'ga pake lama', 'rangkap 10', '', '', '', '10000', '45000', '0', '0', 'std', '2', '1', '1', '0', '1', '10', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('1', '2', 'Ulang Tahun ke 100', '500', 'lembar', 'susah susah gampang', 'jangan lupa di potong belah 10', '', '', '', '100000', '120000', '0', '0', 'std', '3', '2', '1', '0', '2', '10', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('2', '2', 'Konica Minolta 1060', '20', 'lembar', 'mau di pake besok pagi', 'siap cetak langsung siap siap', '', '', '', '20000', '35000', '0', '0', 'std', '1', '6', '1', '0', '1', '12', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('2', '1', 'Pernikahan yg ke-5', '37', 'lembar', 'ga boleh jelek sama sekali ya', 'yang kuning mau di lipat, yang ijo mau di buang', '', '', '', '220300', '500000', '200000', '0', 'std', '0', '1', '1', '1', '1', '98', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('3', '2', 'Laravel 5.6', '525', 'lembar', 'ingat! jokowi presiden', '', 'siti', '021 6481291', '', '1200300', '2000000', '123000', '2000', 'exp', '2', '1', '1', '1', '1', '76', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('4', '1', 'Sumpah Gw Ga Percaya', '750', 'lembar', 'salam prabowosandi', '', 'soto', '021 67803993', 'Jl. Grogol Jaya 1 No. 123-124', '1500000', '1850000', '35000', '20000', 'exp', '3', '2', '1', '3', '1', '53', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '3', 'Flip Burger', '5000', 'pcs', '2019 ganti presiden', '', 'solo', '021 999 00 991', '', '2300000', '2600000', '12000', '200000', 'exp', '2', '5', '1', '2', '20', '90', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '4', 'Sambal Cap Jempoleee', '2', 'box', '', 'ga usa pake tinta cetaknya', 'Gogo Shop Centre', '0815-9932-2293', 'Jl. Gogo Sebelah Gigi Tetangga Gaga Yang Gambarnya Gagu No. 12', '725000', '1000000', '0', '30000', 'std', '2', '4', '1', '1', '5', '13', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '4', 'Aqua dan Laundry Kiloan', '7', 'box', '', 'numeratornya pake angka, jangan pake pantat', '', '', '', '125000', '1000000', '0', '10500', 'std', '5', '3', '1', '5', '7', '14', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('6', '2', 'Cap Kaki Tiga Warna Biru', '900', 'lembar', '', 'mang sahlan presidenku', '', '', '', '980000', '1000000', '70000', '12500', 'exp', '10', '5', '1', '4', '5', '26', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('6', '6', 'Jokowi Presiden Gw', '123', 'pcs', '', 'mang alex jagoan gw', '', '', '', '38000', '50000', '89000', '0', 'std', '12', '6', '1', '0', '5', '19', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '1', 'Kartu Mahasiswa Binus', '20000', 'lembar', '', '', '', '', '', '25000', '50000', '65000', '0', 'exp', '2', '3', '1', '3', '5', '90', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '7', 'Daikin AC Terbaik', '7500', 'pcs', 'ahok jadi wapres', '', '', '', '', '124000', '350000', '2000', '0', 'exp', '5', '1', '1', '1', '1', '1028', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddressID, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '8', '2019 Ganti Vespa', '2', 'pcs', 'go go go septi tai', '', '', '', '', '12450000', '12980000', '1000', '0', 'exp', '12', '1', '1', '1', '1', '1024', '1', now(), now(), null);
		");
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		//
	}
}
