<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertTambahan2 extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::unprepared("
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('1', '1', 'Lebaran Haji 2018', '1000', 'lembar', 'ga pake lama', 'rangkap 10', '', '', '', '10000', '45000', '0', '0', 'std', '2', '1', 'Jakarta', '0', '1', '10', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('1', '2', 'Ulang Tahun ke 100', '500', 'lembar', 'susah susah gampang', 'jangan lupa di potong belah 10', '', '', '', '100000', '120000', '0', '0', 'std', '3', '2', 'Jatim', '0', '2', '10', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('2', '2', 'Konica Minolta 1060', '20', 'lembar', 'mau di pake besok pagi', 'siap cetak langsung siap siap', '', '', '', '20000', '35000', '0', '0', 'std', '1', '6', 'Jabar', '0', '1', '12', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('2', '1', 'Pernikahan yg ke-5', '37', 'lembar', 'ga boleh jelek sama sekali ya', 'yang kuning mau di lipat, yang ijo mau di buang', '', '', '', '220300', '500000', '200000', '0', 'std', '0', '1', 'Jakut', '1', '1', '98', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('3', '2', 'Laravel 5.6', '525', 'lembar', 'ingat! jokowi presiden', '', 'siti', '021 6481291', '', '1200300', '2000000', '123000', '2000', 'exp', '2', '1', 'Jakarta Pusat', '1', '1', '76', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('4', '1', 'Sumpah Gw Ga Percaya', '750', 'lembar', 'salam prabowosandi', '', 'soto', '021 67803993', 'Jl. Grogol Jaya 1 No. 123-124', '1500000', '1850000', '35000', '20000', 'exp', '3', '2', 'Tanjung Bintan', '3', '1', '53', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '3', 'Flip Burger', '5000', 'pcs', '2019 ganti presiden', '', 'solo', '021 999 00 991', '', '2300000', '2600000', '12000', '200000', 'exp', '2', '5', 'Tanjung Priok', '2', '20', '90', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '4', 'Sambal Cap Jempoleee', '2', 'box', '', 'ga usa pake tinta cetaknya', 'Gogo Shop Centre', '0815-9932-2293', 'Jl. Gogo Sebelah Gigi Tetangga Gaga Yang Gambarnya Gagu No. 12', '725000', '1000000', '0', '30000', 'std', '2', '4', 'Tanjung Bra', '1', '5', '13', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('5', '4', 'Aqua dan Laundry Kiloan', '7', 'box', '', 'numeratornya pake angka, jangan pake pantat', '', '', '', '125000', '1000000', '0', '10500', 'std', '5', '3', 'Bunga Pepaya', '5', '7', '14', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('6', '2', 'Cap Kaki Tiga Warna Biru', '900', 'lembar', '', 'mang sahlan presidenku', '', '', '', '980000', '1000000', '70000', '12500', 'exp', '10', '5', 'Menteng', '4', '5', '26', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('6', '6', 'Jokowi Presiden Gw', '123', 'pcs', '', 'mang alex jagoan gw', '', '', '', '38000', '50000', '89000', '0', 'std', '12', '6', 'Sumpah gw lUpa', '0', '5', '19', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '1', 'Kartu Mahasiswa Binus', '20000', 'lembar', '', '', '', '', '', '25000', '50000', '65000', '0', 'exp', '2', '3', 'Php My Admin', '3', '5', '90', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '7', 'Daikin AC Terbaik', '7500', 'pcs', 'ahok jadi wapres', '', '', '', '', '124000', '350000', '2000', '0', 'exp', '5', '1', 'Tes dong bro', '1', '1', '1028', '1', now(), now(), null);
			INSERT INTO cartheaders(customerID, jobsubtypeID, jobtitle, quantity, quantitytypename, customernote, itemdescription, resellername, resellerphone, reselleraddress, buyprice, printprice, deliveryprice, discount, processtype, processtime, deliveryID, deliveryaddress, deliverytime, totalpackage, totalweight, filestatus, created_at, updated_at, deleted_at) VALUES('7', '8', '2019 Ganti Vespa', '2', 'pcs', 'go go go septi tai', '', '', '', '', '12450000', '12980000', '1000', '0', 'exp', '12', '1', '', '1', '1', '1024', '1', now(), now(), null);



			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('15', 'Main', 'OF', '5', '7', '10', '4', '3.08', '4', '2.08', '2', '4', '0', ' ', '9800', '20', '2450', '4', '1', '4', '0', '19', '3', '6', '1', '13462738', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('16', 'Cover', 'DG', '5', '7', '8', '4', '6.09', '5', '5.09', '2.5', '4', '0', ' ', '4800', '157', '1200', '12', '2', '6', '0', '14', '3', '4', '2', '15628569', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('17', 'Isi', 'DG', '3', '1', '7', '1', '7.6', '6', '6.6', '3', '4', '0', ' ', '3300', '61', '825', '4', '1', '4', '0', '25', '4', '6', '1', '9392235', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('15', 'Isi', 'DG', '4', '6', '1', '5', '6.35', '6', '5.35', '3', '2', '3', ' ', '1100', '22', '275', '9', '3', '3', '0', '8', '1', '8', '0', '14367962', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('16', 'Amplop', 'DG', '3', '7', '1', '2', '6.82', '8', '5.82', '4', '4', '1', ' ', '2700', '189', '675', '9', '3', '3', '0', '17', '2', '8', '1', '18083263', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('4', 'Dalam', 'OF', '1', '1', '9', '7', '7.63', '6', '6.63', '3', '1', '3', ' ', '4300', '198', '1075', '25', '3', '8', '1', '12', '4', '3', '0', '19929345', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('4', 'Luar', 'OF', '5', '6', '7', '7', '7.76', '3', '6.76', '1.5', '1', '0', ' ', '7100', '130', '1775', '21', '4', '5', '1', '8', '2', '3', '2', '18387664', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('5', 'Main', 'DG', '4', '7', '8', '4', '6.85', '6', '5.85', '3', '3', '2', ' ', '2000', '140', '500', '18', '3', '6', '0', '15', '2', '7', '1', '19140449', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('6', 'Main', 'OF', '3', '2', '4', '1', '3.21', '6', '2.21', '3', '3', '0', ' ', '1800', '92', '450', '9', '1', '8', '1', '4', '2', '1', '2', '8274360', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('7', 'Main', 'DG', '4', '1', '6', '1', '7.08', '6', '6.08', '3', '4', '2', ' ', '7400', '37', '1850', '6', '2', '3', '0', '22', '3', '7', '1', '1481583', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('8', 'Main', 'OF', '2', '6', '8', '6', '7.84', '8', '6.84', '4', '1', '0', ' ', '1300', '63', '325', '17', '2', '8', '1', '5', '2', '2', '1', '14351496', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('9', 'Main', 'OF', '2', '7', '9', '3', '5.12', '4', '4.12', '2', '3', '3', ' ', '3500', '130', '875', '2', '1', '2', '0', '20', '3', '6', '2', '11328714', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('10', 'Main', 'PL', '3', '5', '8', '1', '4.71', '1', '3.71', '0.5', '2', '1', ' ', '3000', '46', '750', '15', '3', '5', '0', '16', '3', '5', '1', '7489629', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('11', 'Main', 'PL', '3', '5', '2', '1', '3.03', '6', '2.03', '3', '4', '3', ' ', '5400', '34', '1350', '8', '1', '8', '0', '5', '2', '2', '1', '3159712', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('12', 'Main', 'PL', '2', '5', '5', '7', '5.49', '3', '4.49', '1.5', '2', '0', ' ', '2800', '132', '700', '25', '4', '6', '1', '4', '4', '1', '0', '9557715', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('13', 'Main', 'LL', '1', '1', '8', '4', '5.65', '3', '4.65', '1.5', '2', '1', ' ', '9900', '50', '2475', '9', '4', '2', '1', '16', '2', '8', '0', '14910494', now(), now());
			INSERT INTO cartdetails(cartID, cartname, jobtype, printerID, paperID, vendorID, planoID, printwidth, printlength, imagewidth, imagelength, side1, side2, employeenote, totaldruct, inschiet, totalplano, totalinplano, totalinplanox, totalinplanoy, totalinplanorest, totalinprint, totalinprintx, totalinprinty, totalinprintrest, totalpaperprice, created_at, updated_at) VALUES ('14', 'Main', 'LL', '6', '5', '1', '5', '1.69', '6', '0.69', '3', '1', '1', ' ', '3000', '198', '750', '9', '1', '8', '1', '29', '4', '7', '1', '8033588', now(), now());

			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('3', '15', '2', '1', '1', '1', '1', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('4', '16', '2', '1', '1', '0', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('3', '17', '2', '1', '1', '1', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('3', '4', '2', '1', '1', '1', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('5', '5', '2', '1', '1', '1', '1', '1', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('6', '6', '2', '1', '1', '1', '1', '1', '1', '1', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('7', '7', '2', '1', '1', '0', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('8', '8', '2', '1', '1', '0', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('6', '9', '1', '1', '1', '0', '0', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('7', '10', '1', '1', '1', '1', '1', '1', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('7', '11', '2', '1', '1', '1', '1', '1', '1', '1', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('6', '12', '2', '1', '1', '1', '1', '1', '1', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('8', '13', '2', '1', '1', '1', '1', '0', '0', '0', now(), now());
			INSERT INTO salesdetails (salesID, cartID, prioritylevel, statusfile, commited, statusctp, statusprint, statuspacking, statusdelivery, statusdone, created_at, updated_at) VALUES ('4', '14', '2', '1', '1', '1', '0', '0', '0', '0', now(), now());
		");
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		//
	}
}
